# Auto-generated by scripts/generate-sdk-actions.py — do not edit manually.

"""All valid compliance action constants for AuditRails."""

from typing import Literal


class Actions:
    """Compliance action constants grouped by category.

    Usage: auditrails.log(action=Actions.AUTH_LOGIN, ...)
    """

    # Access Control
    ACCESS_GRANTED: str = 'access.granted'
    ACCESS_REVOKED: str = 'access.revoked'
    PERMISSION_GRANTED: str = 'permission.granted'

    # Asset Management
    ASSET_REGISTERED: str = 'asset.registered'

    # Authentication
    AUTH_FAILED: str = 'auth.failed'
    AUTH_LOGIN: str = 'auth.login'
    AUTH_LOGOUT: str = 'auth.logout'
    AUTH_MFA: str = 'auth.mfa'

    # Breach
    BREACH_DETECTED: str = 'breach.detected'
    BREACH_NOTIFIED: str = 'breach.notified'

    # Business Continuity
    BACKUP_COMPLETED: str = 'backup.completed'

    # Change Management
    CHANGE_APPROVED: str = 'change.approved'
    CONFIG_CHANGED: str = 'config.changed'

    # Compliance
    AUDIT_COMPLETED: str = 'audit.completed'
    COMPLIANCE_REPORT: str = 'compliance.report'

    # Configuration Management
    DEPLOY_COMPLETED: str = 'deploy.completed'

    # Consent Management
    CONSENT_GIVEN: str = 'consent.given'
    CONSENT_WITHDRAWN: str = 'consent.withdrawn'

    # Consumer Rights
    DATA_ACCESSED: str = 'data.accessed'
    DATA_DELETED: str = 'data.deleted'
    DATA_UPDATED: str = 'data.updated'
    PRIVACY_REQUEST: str = 'privacy.request'

    # Data Access
    CARDHOLDER_ACCESSED: str = 'cardholder.accessed'

    # Data Portability
    DATA_EXPORTED: str = 'data.exported'

    # Data Sharing
    DATA_SHARED: str = 'data.shared'

    # Data Subject Rights
    DSAR_COMPLETED: str = 'dsar.completed'
    DSAR_RECEIVED: str = 'dsar.received'

    # Encryption
    ENCRYPTION_STATUS: str = 'encryption.status'

    # Governance
    TRAINING_COMPLETED: str = 'training.completed'

    # Incident Management
    INCIDENT_DETECTED: str = 'incident.detected'
    INCIDENT_NOTIFIED: str = 'incident.notified'
    INCIDENT_RESOLVED: str = 'incident.resolved'

    # Network Security
    FIREWALL_CHANGED: str = 'firewall.changed'

    # Phi Access
    PHI_ACCESSED: str = 'phi.accessed'
    PHI_AMENDED: str = 'phi.amended'
    PHI_DISCLOSED: str = 'phi.disclosed'

    # Processing
    PROCESSING_STARTED: str = 'processing.started'
    PROCESSING_STOPPED: str = 'processing.stopped'

    # Resilience Testing
    VULNERABILITY_SCAN: str = 'vulnerability.scan'

    # Retention
    RETENTION_EXPIRED: str = 'retention.expired'

    # Risk Management
    RISK_ASSESSED: str = 'risk.assessed'

    # Vulnerability Management
    PATCH_APPLIED: str = 'patch.applied'


# Type alias for type checkers — accepts any valid compliance action string.
ComplianceAction = Literal[
    "access.granted",
    "access.revoked",
    "permission.granted",
    "asset.registered",
    "auth.failed",
    "auth.login",
    "auth.logout",
    "auth.mfa",
    "breach.detected",
    "breach.notified",
    "backup.completed",
    "change.approved",
    "config.changed",
    "audit.completed",
    "compliance.report",
    "deploy.completed",
    "consent.given",
    "consent.withdrawn",
    "data.accessed",
    "data.deleted",
    "data.updated",
    "privacy.request",
    "cardholder.accessed",
    "data.exported",
    "data.shared",
    "dsar.completed",
    "dsar.received",
    "encryption.status",
    "training.completed",
    "incident.detected",
    "incident.notified",
    "incident.resolved",
    "firewall.changed",
    "phi.accessed",
    "phi.amended",
    "phi.disclosed",
    "processing.started",
    "processing.stopped",
    "vulnerability.scan",
    "retention.expired",
    "risk.assessed",
    "patch.applied"
]
